### ISSUE TITLE
clcoagTend output looks bizarre 

### ISSUE THREAD

**Issue by sarambl** [NorESMhub/CAM#24] opened 2020-08-13 12:19 UTC
Hi all!
I had a quick look at the SOA_NAclcoagTend from a run I did and the other clcoagTend outputs and they look like they have some kind of numerical issue, possibly on top of the real values. 
I also checked the aerocom runs that @Kirkevag did and it seems to have the same issues. 
/projects/NS2345K/noresm/cases/NFHISTnorpddmsbcsdyn_f09_mg17_20191101

![image](https://user-images.githubusercontent.com/17406708/90132718-97bb5880-dd6e-11ea-8e15-3e5d42c7b4ea.png)

**Comment by gold2718** [comment] 2023-06-08 08:29
@DirkOlivie , can you have a look at this in a recent run so we can see if it is fixed or needs to be fixed?

**Comment by oyvindseland** [comment] 2023-06-23 07:50
I looked into the problem and I see it although slightly different in the historical CMIP6 simulations. It is not present in the Forces simulation even though there should not be any changes to this part. Vilje vs Betzy initialisation ?

**Comment by oyvindseland** [comment] 2023-08-16 13:01
I checked the results more thoroughly and the problem is indeed still there.

**Comment by oyvindseland** [comment] 2023-09-07 08:12
Likely an error in use of columns indices. No unphysical values, but some zero values that should be non-zero. If so it will change the answer.

**Comment by oyvindseland** [comment] 2023-10-24 13:28
Hi

The error is not as straightforward as I thought, but based on results presented by Dirk and also the fact that the aerosol used inside these calculations seem to be quite dependent on core count, I think there is likely an error in the arrays that is communicated to the subroutine. module koagsub --< subroutine clcoag

**Comment by gold2718** [comment] 2023-10-24 14:23
This is interesting. In our reproducibility testing and code review, we have found some bugs in the coag code (along with hetfrz). Doing some testing now but should have a version to look at soon. We need to discuss!

**Comment by oyvindseland** [comment] 2023-10-27 10:20
The bug that was found in the code is the same that is giving strange output. Ie. the problem was not the output but the calculation. The fields looks correct after the bugfix

**Comment by gold2718** [comment] 2023-11-24 12:52
fixed in #116

**Closed by gold2718** 2023-11-24 12:52 UTC
Labels: bug
